# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "elasticsearch.local"
  config.vm.network :private_network, ip: "33.33.22.101"

  config.vm.box = "chef/ubuntu-14.04"

  config.vm.provider :virtualbox do |vb|
      # Properly configure the vm to use the available amount of cores
      vb.customize ["modifyvm", :id, "--cpus", `#{RbConfig::CONFIG['host_os'] =~ /darwin/ ? 'sysctl -n hw.ncpu' : 'nproc'}`.chomp]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]

      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "automation/vagrant"
      ansible.limit = "all"
      ansible.playbook = "automation/provision.yml"
      ansible.verbose = false
  end
end
